sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
script:
  - sed -i "s/yuque_token/$YUQUE_TOKEN/g" package.json
  - npm run sync
  - hexo recommend
  - cat source/_data/recommended_posts.json
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: hexo
  target_branch: master
  local-dir: public