baseURL = 'https://gomi1992.github.io/'
languageCode = 'en-us'
title = 'GoMi_Field'

canonifyurls = false
paginate = 10
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = 'manni'


[markup.goldmark]
  [markup.goldmark.extensions]
    typographer = false
  [markup.goldmark.renderer]
    unsafe= true

[permalinks]
  post = "/:year/:month/:day/:filename/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[indexes]
  tag = "tags"
  topic = "categories"


[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "归档"
    identifier = "post"
    url = "/post/"
    weight = 1
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "关于"
    identifier = "about"
    url = "/about/"
    weight = 3

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # Techie
  github = "https://github.com/gomi1992"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  math = true
  env = "production"
  description = """
  那里的颜色正是常磐色。
  """
  favicon = "img/favicon.png"
  fuse = true 
  useChineseFonts = true
  bannerFont = "fonts/杨任东竹石体-Light"