# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]
  workflow_dispatch:
    inputs:
      msg:
        description: 'Message'     
        default: 'hello'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        ref: hexo
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 12.x 
      uses: actions/setup-node@master
      with:
        node-version: "12.x"
        
    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g
        npm install
        npm install hexo-deployer-git --save
    - name: generate
      env:
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN}}
        ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "ilalh2owei@163.com"
        git config --global user.name "GoMi"
        sed -i "s/yuque_token/$YUQUE_TOKEN/g" package.json
        npm run sync
        hexo recommend
        cat source/_data/recommended_posts.json
        hexo generate
        
    - name: Deploy
      run: |
          hexo clean
          hexo deploy
